<?php include __DIR__ . '/../layout/header.phtml' ?>

<div class="col-xs-12 col-sm-6 col-md-4">
	
	<form method="POST" action="<?= url('prisijungti') ?>">
	  <div class="form-group">
	    <label for="exampleInputEmail1">Email address</label>
	    <input type="email" class="form-control" name="email" id="exampleInputEmail1" placeholder="Email">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password</label>
	    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
	  </div>
	 
	  <button type="submit" class="btn btn-default">Submit</button>
	</form>
	
</div>	

<?php include __DIR__ . '/../layout/footer.phtml' ?>
