<?php include __DIR__ . '/../layout/header.phtml' ?>
        
<div class="col-xs-12 col-sm-6 col-md-4">
	<form method="POST" action="<?= url('prideti-irasa') ?>">
		<div class="form-group">
		    <label for="exampleInputEmail2">Pavadinimas</label>
		    <input type="text" class="form-control" name="pavadinimas" id="exampleInputEmail2" >
		</div>
	  	<div class="form-group">
		    <label for="exampleInputEmail2">Turinys</label>
			<textarea name="turinys" class="form-control" id="exampleInputEmail2"></textarea>
		</div>
	 
	  <button type="submit" class="btn btn-default">Submit</button>
	</form>
	
</div>	
     
<?php include __DIR__ . '/../layout/footer.phtml' ?>

  