<?php include __DIR__ . '/../layout/header.phtml' ?>
   
   <style>
   	.block {
   		border: #dedede 1px solid;
   	}
   </style>
        
<?php foreach($irasai as $key => $irasas): ?>
	<div class="block col-xs-12 col-sm-4">
		<h3><?= $irasas['pavadinimas'] ?></h3>
		
		<p><?= $irasas['turinys'] ?></p>
		
		<address><?= $irasas['autorius'] ?></address>
		<?php if($irasas['galiIstrinti']): ?>
		<a href="<?= url('pasalinti-irasa') ?>&irasas=<?= $key ?>">Pasalinti</a>
		<?php endif; ?>
	</div>
<?php endforeach; ?>
     
<?php include __DIR__ . '/../layout/footer.phtml' ?>

  