<?php include __DIR__ . '/../layout/header.phtml' ?>
        
<div class="col-xs-12 col-sm-6 col-md-4">
	<form method="POST" action="<?= url('registruoti') ?>">
		<div class="form-group">
	    <label for="exampleInputEmail2">Vardas</label>
	    <input type="text" class="form-control" name="vardas" id="exampleInputEmail2" placeholder="Vardas">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputEmail1">Email address</label>
	    <input type="email" class="form-control" name="email" id="exampleInputEmail1" placeholder="Email">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password</label>
	    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
	  </div>
	    <div class="form-group">
	    <label for="exampleInputPassword1">Password2</label>
	    <input type="password" name="password2" class="form-control" id="exampleInputPassword1" placeholder="Password">
	  </div>
	  
	  	<div class="form-group">
	    <label for="exampleInputEmail3">Amzius</label>
	    <input type="number" class="form-control" name="amzius" id="exampleInputEmail3" placeholder="Email">
	  </div>
	 
	  <button type="submit" class="btn btn-default">Submit</button>
	</form>
	
</div>	
     
<?php include __DIR__ . '/../layout/footer.phtml' ?>

  