<?php include_once 'header.php'; ?>
<h2 class="middle-h2">Calendar</h2>
<div class="container">
    <div class="row">
        <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
            <ul class="event-list">
                <?php foreach ($adresatai as $event): ?>
                <li>
                    <?php $data = explode('-',$event->getData()); ?>
                    <time datetime="<?php echo $event->getData() ?>">
                        <span class="day"><?php echo $data[2]?></span>
                        <span class="month"><?php echo $data[1]?></span>
                        <span class="year"><?php echo $data[0]?></span>
                    </time>
                    <div class="info">
                        <h2 class="title"><?php echo $event->getPavadinimas() ?></h2>
                        <p class="desc">
                            Info:<?php echo $event->getInfo() ?><br/>
                            Vieta: <?php echo $event->getVieta() ?> / Sunkumas:<?php echo $event->getSunkumas()?>/ Kategorija: <?php echo $event->getKategorija() ?>
                        </p>
                        <ul>
                            <li style="width:50%;"><a href="http://<?= $event->getKontaktai()?>"><span class="fa fa-globe"></span> Website</a></li>
                        </ul>
                    </div>
                    <div class="social">
                        <ul>
                            <li class="facebook" style="width:33%;"><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
                            <li class="twitter" style="width:34%;"><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
                            <li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
                        </ul>
                    </div>
                </li>

                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>


<?php include_once 'footer.php'?>
